### ISSUE TITLE
Proposal to add `yielder.prepend`

### ISSUE THREAD

**Issue by JosephTLyons** [gleam-lang/yielder#1]
I'm proposing there be a `prepend` function in `yielder`.  The `yielder` API seems to closely match the `list` API. `list` has [`prepend`](https://hexdocs.pm/gleam_stdlib/gleam/list.html#prepend). Additionally, `yielder` has [`yield`](https://hexdocs.pm/gleam_yielder/gleam/yielder.html#yield), which does a prepend, but is a bit awkward to use in pipes. A `prepend` method would be convenient and as simple as:

```gleam
pub fn prepend(yielder: Yielder(a), element: a) -> Yielder(a) {
  use <- yielder.yield(element)
  yielder
}
```

**Comment by lpil** [comment]
Sounds fab to me!

**Comment by JosephTLyons** [comment]
Would it be sufficient to just do exactly what the example above shows? Or would you want to avoid that and construct the yielder with more low-level primitives? ie, doing what `yield` does under the hood.

At any rate, I could open a PR.
